#!/usr/bin/env bash
# =============================================================================
# install_service.sh — Register base-inference as a systemd service
# =============================================================================
#
# Generates a systemd unit file that ensures the server starts on boot.
# Must be run as root (called via ``sudo ./base-inference service install``).
#
# The unit uses Type=oneshot with RemainAfterExit=yes so systemd considers
# the service active even after ``docker compose up -d`` exits. Docker's
# ``restart: unless-stopped`` then handles individual container recovery.
# =============================================================================

set -euo pipefail

# ── Paths ────────────────────────────────────────────────────────────────────

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
UNIT_NAME="base-inference"
UNIT_FILE="/etc/systemd/system/${UNIT_NAME}.service"

# Until 2026-09-10 this unit was called idia-server.service. A host provisioned
# before that keeps the old unit, and installing the new one beside it leaves
# two units bringing up the same stack — the older one silently winning on the
# next boot. Renaming the variable above is not enough; the old unit has to be
# taken off the host.
LEGACY_UNIT_NAME="idia-server"
LEGACY_UNIT_FILE="/etc/systemd/system/${LEGACY_UNIT_NAME}.service"

# ── Colours ──────────────────────────────────────────────────────────────────

if [ -t 1 ] && command -v tput &>/dev/null; then
    GREEN="$(tput setaf 2)"
    YELLOW="$(tput setaf 3)"
    RESET="$(tput sgr0)"
else
    GREEN="" YELLOW="" RESET=""
fi

_info()  { echo "${GREEN}[✓]${RESET} $*"; }
_warn()  { echo "${YELLOW}[⚠]${RESET} $*"; }

# ── Pre-flight checks ────────────────────────────────────────────────────────

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root. Use:  sudo ./base-inference service install" >&2
    exit 1
fi

if [ ! -f "$REPO_DIR/docker-compose.yml" ]; then
    echo "docker-compose.yml not found at $REPO_DIR — wrong directory?" >&2
    exit 1
fi

# ── Migrate away from the pre-rename unit ────────────────────────────────────

if [ -f "$LEGACY_UNIT_FILE" ]; then
    _warn "found the pre-rename unit ${LEGACY_UNIT_NAME}.service — removing it"
    systemctl disable --now "${LEGACY_UNIT_NAME}.service" 2>/dev/null || true
    rm -f "$LEGACY_UNIT_FILE"
    systemctl daemon-reload
    _info "${LEGACY_UNIT_NAME}.service removed; ${UNIT_NAME}.service replaces it"
fi

# ── Generate unit file ───────────────────────────────────────────────────────

cat > "$UNIT_FILE" << UNITEOF
# base-inference — systemd unit (generated by install_service.sh)
# Do NOT edit manually. Run \`sudo ./base-inference service uninstall\` to remove.

[Unit]
Description=base-inference — LLM Inference Stack
Documentation=https://github.com/PUC-Behring-AI/base-inference
Wants=docker.service
After=docker.service network-online.target
RequiresMountsFor=/var/lib/docker

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${REPO_DIR}
ExecStart=/bin/bash ${REPO_DIR}/base-inference deploy local --no-wait
ExecStop=/bin/bash ${REPO_DIR}/base-inference stop
Restart=on-failure
RestartSec=30
TimeoutStartSec=900
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNITEOF

_info "Unit file written: $UNIT_FILE"

# ── Register with systemd ────────────────────────────────────────────────────

systemctl daemon-reload
_info "systemd daemon reloaded"

systemctl enable "$UNIT_NAME"
_info "Service enabled — starts automatically on boot"

# ── Start the service now ────────────────────────────────────────────────────

echo ""
echo "Starting service now..."
if systemctl start "$UNIT_NAME"; then
    _info "Service started"
else
    _warn "Service start failed — check logs with:  journalctl -u $UNIT_NAME -f"
    exit 1
fi

echo ""
echo "${GREEN}══════════════════════════════════════${RESET}"
echo "${GREEN}  base-inference service installed${RESET}"
echo "${GREEN}══════════════════════════════════════${RESET}"
echo ""
echo "  Status:      ./base-inference service status"
echo "  Logs:        journalctl -u $UNIT_NAME -f"
echo "  Stop:        sudo systemctl stop $UNIT_NAME"
echo "  Uninstall:   sudo ./base-inference service uninstall"
echo ""
